# Generated by Django 4.2.24 on 2025-10-08 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessmanProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='businessman_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('business_name', models.CharField(max_length=255)),
                ('descriptions', models.TextField()),
                ('contact', models.CharField(max_length=255)),
                ('location_description', models.CharField(blank=True, max_length=255)),
                ('offers_local_products', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='consumer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialistProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='specialist_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profession', models.CharField(help_text='Veterinario, Agronomo, Sistemas, Etc...', max_length=100)),
                ('experience_years', models.IntegerField(default=0)),
                ('about_us', models.TextField(blank=True, verbose_name='Detalles/Acerca de')),
                ('puntuations', models.FloatField(default=0.0)),
                ('point', models.IntegerField(default=0)),
                ('can_give_consultations', models.BooleanField(default=False)),
                ('can_offer_online_services', models.BooleanField(default=False)),
            ],
        ),
    ]
