# Generated by Django 4.2.26 on 2025-11-22 01:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número válido', regex='^\\+?\\d{7,15}$')], verbose_name='phone number')),
                ('role', models.CharField(blank=True, choices=[('Specialist', 'Especialista'), ('businessman', 'Empresario'), ('consumer', 'Consumidor')], max_length=20, null=True, verbose_name='rol')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='nombre')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='apellido')),
                ('profile_picture', models.CharField(blank=True, help_text='URL de la imagen en Supabase', max_length=500, null=True, verbose_name='foto de perfil')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Sobre mi')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='PhoneResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_reset_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código de Reset',
                'verbose_name_plural': 'Códigos de Reset',
                'indexes': [models.Index(fields=['code', 'created_at'], name='auth_app_ph_code_4501ae_idx')],
            },
        ),
    ]
