# Generated by Django 4.2.26 on 2025-11-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessmanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text='ID del usuario en Auth Service', unique=True)),
                ('business_name', models.CharField(max_length=255)),
                ('descriptions', models.TextField()),
                ('contact', models.CharField(max_length=255)),
                ('offers_local_products', models.BooleanField(default=True)),
                ('products_and_services_ids', models.JSONField(blank=True, default=list, help_text='Lista de IDs de media en Media Service')),
            ],
            options={
                'verbose_name': 'Perfil Empresario',
                'verbose_name_plural': 'Perfiles Empresarios',
            },
        ),
        migrations.CreateModel(
            name='ConsumerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text='ID del usuario en Auth Service', unique=True)),
            ],
            options={
                'verbose_name': 'Perfil Consumidor',
                'verbose_name_plural': 'Perfiles Consumidores',
            },
        ),
        migrations.CreateModel(
            name='SpecialistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text='ID del usuario en Auth Service', unique=True)),
                ('profession', models.CharField(help_text='Veterinario, Agronomo, Sistemas, Etc...', max_length=100)),
                ('experience_years', models.IntegerField(default=0)),
                ('about_us', models.TextField(blank=True, verbose_name='Detalles/Acerca de')),
                ('puntuations', models.FloatField(default=0.0)),
                ('point', models.IntegerField(default=0)),
                ('can_give_consultations', models.BooleanField(default=False)),
                ('can_offer_online_services', models.BooleanField(default=False)),
                ('work_images_ids', models.JSONField(blank=True, default=list, help_text='Lista de IDs de media en Media Service')),
            ],
            options={
                'verbose_name': 'Perfil Especialista',
                'verbose_name_plural': 'Perfiles Especialistas',
            },
        ),
    ]
