# Generated by Django 4.2.26 on 2025-11-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_add_verification_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmanprofile',
            name='business_type',
            field=models.CharField(choices=[('Agroveterinaria', 'Agroveterinaria'), ('Empresa Agropecuaria', 'Empresa Agropecuaria')], default='Agroveterinaria', help_text='Tipo de negocio: Agroveterinaria o Empresa Agropecuaria', max_length=100),
        ),
        migrations.AlterField(
            model_name='specialistprofile',
            name='profession',
            field=models.CharField(choices=[('Veterinario', 'Veterinario'), ('Agrónomo', 'Agrónomo'), ('Zootecnista', 'Zootecnista')], help_text='Solo se permiten: Veterinario, Agrónomo o Zootecnista', max_length=100),
        ),
    ]
