# Generated by Django 4.2.26 on 2025-11-23 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('participants_ids', models.JSONField(default=list, help_text='Lista de IDs de participantes en Auth Service')),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sala de Chat',
                'verbose_name_plural': 'Salas de Chat',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField(db_index=True, help_text='ID del remitente en Auth Service')),
                ('content', models.TextField(blank=True, verbose_name='Contenido del mensaje')),
                ('media_id', models.IntegerField(blank=True, help_text='ID de media en Media Service', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora')),
                ('sent', models.BooleanField(default=True, verbose_name='Enviado')),
                ('delivered', models.BooleanField(default=False, verbose_name='Entregado')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora entrega')),
                ('read', models.BooleanField(default=False, verbose_name='Leído')),
                ('seen', models.BooleanField(default=False, verbose_name='Visto')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora lectura')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='ChatMessageReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text='ID del usuario en Auth Service')),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='chat.chatmessage')),
            ],
            options={
                'verbose_name': 'Receipt de mensaje',
                'verbose_name_plural': 'Receipts de mensajes',
                'unique_together': {('message', 'user_id')},
            },
        ),
    ]
