# Generated by Django 5.2.7 on 2025-10-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_media_alter_chatmessage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='Entregado'),
        ),
    ]
