# Generated by Django 4.2.26 on 2025-11-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatmessage_delivered_at_chatmessage_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='Visto'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sent',
            field=models.BooleanField(default=True, verbose_name='Enviado'),
        ),
    ]
