# Generated by Django 4.2.23 on 2025-11-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatmessage_seen_chatmessage_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastRetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(db_index=True, max_length=200)),
                ('payload', models.JSONField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Broadcast retry',
                'verbose_name_plural': 'Broadcast retries',
            },
        ),
    ]
