# Generated by Django 4.2.23 on 2025-10-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(blank=True, help_text='URL de la imagen en Supabase', max_length=500, null=True, verbose_name='foto de perfil'),
        ),
    ]
