# Generated by Django 4.2.26 on 2025-11-30 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text='ID del usuario en Auth Service')),
                ('post_id', models.IntegerField(db_index=True, help_text='ID del post')),
                ('parent_id', models.IntegerField(blank=True, db_index=True, help_text='ID del comentario padre (para respuestas)', null=True)),
                ('content', models.TextField()),
                ('media_id', models.IntegerField(blank=True, help_text='ID de media en Media Service', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reactions_count', models.PositiveIntegerField(default=0)),
                ('replies_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_by_id', models.IntegerField(blank=True, help_text='ID del usuario creador en Auth Service', null=True)),
                ('members_ids', models.JSONField(blank=True, default=list, help_text='Lista de IDs de miembros en Auth Service')),
                ('members_count', models.PositiveIntegerField(default=0)),
                ('cover_image', models.CharField(blank=True, help_text='URL de imagen de portada', max_length=500, null=True)),
                ('avatar', models.CharField(blank=True, help_text='URL de avatar', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comunidad',
                'verbose_name_plural': 'Comunidades',
                'ordering': ['-members_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField(db_index=True, help_text='ID del usuario en Auth Service')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('media_id', models.IntegerField(blank=True, help_text='ID de media en Media Service', null=True)),
                ('community_id', models.IntegerField(blank=True, db_index=True, help_text='ID de comunidad', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('relevance_score', models.FloatField(db_index=True, default=0.0)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.IntegerField(db_index=True, help_text='ID del usuario destinatario en Auth Service')),
                ('actor_id', models.IntegerField(db_index=True, help_text='ID del usuario que realiza la acción en Auth Service')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('notif_type', models.CharField(choices=[('post_reply', 'Reply to post'), ('comment_reply', 'Reply to comment'), ('post_reaction', 'Reaction to post'), ('comment_reaction', 'Reaction to comment')], max_length=32)),
                ('summary', models.CharField(blank=True, max_length=512)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text='ID del usuario en Auth Service')),
                ('type', models.CharField(choices=[('heart', 'Heart'), ('like', 'Like'), ('dislike', 'Dislike')], max_length=16)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Reacción',
                'verbose_name_plural': 'Reacciones',
                'unique_together': {('user_id', 'content_type', 'object_id', 'type')},
            },
        ),
    ]
