"""Make content_type and object_id nullable for Media

Generated by automation to allow creating Media entries before they are
attached to other models (e.g., uploaded to Supabase, then referenced by a
ChatMessage). After applying this migration, `content_type` and `object_id`
may be omitted when creating Media.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="content_type",
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, to="contenttypes.ContentType"),
        ),
        migrations.AlterField(
            model_name="media",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
