# Generated by Django 4.2.26 on 2025-11-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_community_post_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='avatar',
            field=models.CharField(blank=True, help_text='Optional URL for community avatar (round)', max_length=500, null=True),
        ),
    ]
